const champImages = {
    'Aatrox' : require('../../images/lolSquares/AatroxSquare.png'),
    'Ahri' : require('../../images/lolSquares/AhriSquare.png'),
    'Akali' : require('../../images/lolSquares/AkaliSquare.png'),
    'Alistar' : require('../../images/lolSquares/AlistarSquare.png'),
    'Amumu' : require('../../images/lolSquares/AmumuSquare.png'),
    'Anivia' : require('../../images/lolSquares/AniviaSquare.png'),
    'Annie' : require('../../images/lolSquares/AnnieSquare.png'),
    'Ashe' : require('../../images/lolSquares/AsheSquare.png'),
    'Aurelion Sol' : require('../../images/lolSquares/Aurelion_SolSquare.png'),
    'Azir' : require('../../images/lolSquares/AzirSquare.png'),
    'Bard' : require('../../images/lolSquares/BardSquare.png'),
    'Blitzcrank' : require('../../images/lolSquares/BlitzcrankSquare.png'),
    'Brand' : require('../../images/lolSquares/BrandSquare.png'),
    'Braum' : require('../../images/lolSquares/BraumSquare.png'),
    'Caitlyn' : require('../../images/lolSquares/CaitlynSquare.png'),
    'Camille' : require('../../images/lolSquares/CamilleSquare.png'),
    'Cassiopeia' : require('../../images/lolSquares/CassiopeiaSquare.png'),
    'Cho\'Gath' : require('../../images/lolSquares/Cho\'GathSquare.png'),
    'Corki' : require('../../images/lolSquares/CorkiSquare.png'),
    'Darius' : require('../../images/lolSquares/DariusSquare.png'),
    'Diana' : require('../../images/lolSquares/DianaSquare.png'),
    'Dr. Mundo' : require('../../images/lolSquares/Dr._MundoSquare.png'),
    'Draven' : require('../../images/lolSquares/DravenSquare.png'),
    'Ekko' : require('../../images/lolSquares/EkkoSquare.png'),
    'Elise' : require('../../images/lolSquares/EliseSquare.png'),
    'Evelynn' : require('../../images/lolSquares/EvelynnSquare.png'),
    'Ezreal' : require('../../images/lolSquares/EzrealSquare.png'),
    'Fiddlesticks' : require('../../images/lolSquares/FiddlesticksSquare.png'),
    'Fiora' : require('../../images/lolSquares/FioraSquare.png'),
    'Fizz' : require('../../images/lolSquares/FizzSquare.png'),
    'Galio' : require('../../images/lolSquares/GalioSquare.png'),
    'Gangplank' : require('../../images/lolSquares/GangplankSquare.png'),
    'Garen' : require('../../images/lolSquares/GarenSquare.png'),
    'Gnar' : require('../../images/lolSquares/GnarSquare.png'),
    'Gragas' : require('../../images/lolSquares/GragasSquare.png'),
    'Graves' : require('../../images/lolSquares/GravesSquare.png'),
    'Hecarim' : require('../../images/lolSquares/HecarimSquare.png'),
    'Heimerdinger' : require('../../images/lolSquares/HeimerdingerSquare.png'),
    'Illaoi' : require('../../images/lolSquares/IllaoiSquare.png'),
    'Irelia' : require('../../images/lolSquares/IreliaSquare.png'),
    'Ivern' : require('../../images/lolSquares/IvernSquare.png'),
    'Janna' : require('../../images/lolSquares/JannaSquare.png'),
    'Jarvan IV' : require('../../images/lolSquares/Jarvan_IVSquare.png'),
    'Jax' : require('../../images/lolSquares/JaxSquare.png'),
    'Jayce' : require('../../images/lolSquares/JayceSquare.png'),
    'Jhin' : require('../../images/lolSquares/JhinSquare.png'),
    'Jinx' : require('../../images/lolSquares/JinxSquare.png'),
    'Kai\'Sa' : require('../../images/lolSquares/Kai\'SaSquare.png'),
    'Kalista' : require('../../images/lolSquares/KalistaSquare.png'),
    'Karma' : require('../../images/lolSquares/KarmaSquare.png'),
    'Karthus' : require('../../images/lolSquares/KarthusSquare.png'),
    'Kassadin' : require('../../images/lolSquares/KassadinSquare.png'),
    'Katarina' : require('../../images/lolSquares/KatarinaSquare.png'),
    'Kayle' : require('../../images/lolSquares/KayleSquare.png'),
    'Kayn' : require('../../images/lolSquares/KaynSquare.png'),
    'Kennen' : require('../../images/lolSquares/KennenSquare.png'),
    'Kha\'Zix' : require('../../images/lolSquares/Kha\'ZixSquare.png'),
    'Kindred' : require('../../images/lolSquares/KindredSquare.png'),
    'Kled' : require('../../images/lolSquares/KledSquare.png'),
    'Kog\'Maw' : require('../../images/lolSquares/Kog\'MawSquare.png'),
    'LeBlanc' : require('../../images/lolSquares/LeBlancSquare.png'),
    'Lee Sin' : require('../../images/lolSquares/Lee_SinSquare.png'),
    'Leona' : require('../../images/lolSquares/LeonaSquare.png'),
    'Lissandra' : require('../../images/lolSquares/LissandraSquare.png'),
    'Lucian' : require('../../images/lolSquares/LucianSquare.png'),
    'Lulu' : require('../../images/lolSquares/LuluSquare.png'),
    'Lux' : require('../../images/lolSquares/LuxSquare.png'),
    'Malphite' : require('../../images/lolSquares/MalphiteSquare.png'),
    'Malzahar' : require('../../images/lolSquares/MalzaharSquare.png'),
    'Maokai' : require('../../images/lolSquares/MaokaiSquare.png'),
    'Master Yi' : require('../../images/lolSquares/Master_YiSquare.png'),
    'Miss Fortune' : require('../../images/lolSquares/Miss_FortuneSquare.png'),
    'Mordekaiser' : require('../../images/lolSquares/MordekaiserSquare.png'),
    'Morgana' : require('../../images/lolSquares/MorganaSquare.png'),
    'Nami' : require('../../images/lolSquares/NamiSquare.png'),
    'Nasus' : require('../../images/lolSquares/NasusSquare.png'),
    'Nautilus' : require('../../images/lolSquares/NautilusSquare.png'),
    'Nidalee' : require('../../images/lolSquares/NidaleeSquare.png'),
    'Nocturne' : require('../../images/lolSquares/NocturneSquare.png'),
    'Nunu' : require('../../images/lolSquares/NunuSquare.png'),
    'Olaf' : require('../../images/lolSquares/OlafSquare.png'),
    'Orianna' : require('../../images/lolSquares/OriannaSquare.png'),
    'Ornn' : require('../../images/lolSquares/OrnnSquare.png'),
    'Pantheon' : require('../../images/lolSquares/PantheonSquare.png'),
    'Poppy' : require('../../images/lolSquares/PoppySquare.png'),
    'Quinn' : require('../../images/lolSquares/QuinnSquare.png'),
    'Rakan' : require('../../images/lolSquares/RakanSquare.png'),
    'Rammus' : require('../../images/lolSquares/RammusSquare.png'),
    'Rek\'Sai' : require('../../images/lolSquares/Rek\'SaiSquare.png'),
    'Renekton' : require('../../images/lolSquares/RenektonSquare.png'),
    'Rengar' : require('../../images/lolSquares/RengarSquare.png'),
    'Riven' : require('../../images/lolSquares/RivenSquare.png'),
    'Rumble' : require('../../images/lolSquares/RumbleSquare.png'),
    'Ryze' : require('../../images/lolSquares/RyzeSquare.png'),
    'Sejuani' : require('../../images/lolSquares/SejuaniSquare.png'),
    'Shaco' : require('../../images/lolSquares/ShacoSquare.png'),
    'Shen' : require('../../images/lolSquares/ShenSquare.png'),
    'Shyvana' : require('../../images/lolSquares/ShyvanaSquare.png'),
    'Singed' : require('../../images/lolSquares/SingedSquare.png'),
    'Sion' : require('../../images/lolSquares/SionSquare.png'),
    'Sivir' : require('../../images/lolSquares/SivirSquare.png'),
    'Skarner' : require('../../images/lolSquares/SkarnerSquare.png'),
    'Sona' : require('../../images/lolSquares/SonaSquare.png'),
    'Soraka' : require('../../images/lolSquares/SorakaSquare.png'),
    'Swain' : require('../../images/lolSquares/SwainSquare.png'),
    'Syndra' : require('../../images/lolSquares/SyndraSquare.png'),
    'Tahm Kench' : require('../../images/lolSquares/Tahm_KenchSquare.png'),
    'Talyah' : require('../../images/lolSquares/TaliyahSquare.png'),
    'Talon' : require('../../images/lolSquares/TalonSquare.png'),
    'Taric' : require('../../images/lolSquares/TaricSquare.png'),
    'Teemo' : require('../../images/lolSquares/TeemoSquare.png'),
    'Thresh' : require('../../images/lolSquares/ThreshSquare.png'),
    'Tristana' : require('../../images/lolSquares/TristanaSquare.png'),
    'Trundle' : require('../../images/lolSquares/TrundleSquare.png'),
    'Tryndamere' : require('../../images/lolSquares/TryndamereSquare.png'),
    'Twisted Fate' : require('../../images/lolSquares/Twisted_FateSquare.png'),
    'Twitch' : require('../../images/lolSquares/TwitchSquare.png'),
    'Udyr' : require('../../images/lolSquares/UdyrSquare.png'),
    'Urgot' : require('../../images/lolSquares/UrgotSquare.png'),
    'Varus' : require('../../images/lolSquares/VarusSquare.png'),
    'Vayne' : require('../../images/lolSquares/VayneSquare.png'),
    'Veigar' : require('../../images/lolSquares/VeigarSquare.png'),
    'Vel\'Koz' : require('../../images/lolSquares/Vel\'KozSquare.png'),
    'Vi' : require('../../images/lolSquares/ViSquare.png'),
    'Viktor' : require('../../images/lolSquares/ViktorSquare.png'),
    'Vladimir' : require('../../images/lolSquares/VladimirSquare.png'),
    'Volibear' : require('../../images/lolSquares/VolibearSquare.png'),
    'Warwick' : require('../../images/lolSquares/WarwickSquare.png'),
    'Wukong' : require('../../images/lolSquares/WukongSquare.png'),
    'Xayah' : require('../../images/lolSquares/XayahSquare.png'),
    'Xerath' : require('../../images/lolSquares/XerathSquare.png'),
    'Xin Zhao' : require('../../images/lolSquares/Xin_ZhaoSquare.png'),
    'Yasuo' : require('../../images/lolSquares/YasuoSquare.png'),
    'Yorick' : require('../../images/lolSquares/YorickSquare.png'),
    'Zac' : require('../../images/lolSquares/ZacSquare.png'),
    'Zed' : require('../../images/lolSquares/ZedSquare.png'),
    'Ziggs' : require('../../images/lolSquares/ZiggsSquare.png'),
    'Zilean' : require('../../images/lolSquares/ZileanSquare.png'),
    'Zoe' : require('../../images/lolSquares/ZoeSquare.png'),
    'Zyra' : require('../../images/lolSquares/ZyraSquare.png')
  }

const rankImages = {
  'Unranked' : require('../../images/rank/UnrankedBadge.png'),
  'BRONZE' : require('../../images/rank/BronzeBadge.png'),
  'SILVER' : require('../../images/rank/SilverBadge.png'),
  'GOLD' : require('../../images/rank/GoldBadge.png'),
  'PLATINUM' : require('../../images/rank/PlatinumBadge.png'),
  'DIAMOND' : require('../../images/rank/DiamondBadge.png'),
  'MASTER' : require('../../images/rank/MasterBadge.png'),
  'CHALLENGER' : require('../../images/rank/ChallengerBadge.png')
}

export {rankImages, champImages}

